name: Fly Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install dependencies
        run: npm i

      - name: Push to Fly
        uses: superfly/flyctl-actions@1.0
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: 'deploy'
